=== aloka-ts/CASGitRepo/src/com/baypackets/ase/testapps/b2b/WEB-INF/b2b-config.dtd
<!ELEMENT b2b-config (sleep-intervals?, request-forwardings, cdr?)>

<!ELEMENT sleep-intervals (request*, response*)>

<!ELEMENT request (#PCDATA)>

<!ELEMENT response (#PCDATA)>

<!ELEMENT request-forwardings (request-forwarding+)>

<!ELEMENT request-forwarding (incoming-ip, outbound-ip, outbound-port, outbound-user?)>

<!ELEMENT incoming-ip (#PCDATA)>

<!ELEMENT outbound-ip (#PCDATA)>

<!ELEMENT outbound-port (#PCDATA)>

<!ELEMENT outbound-user (#PCDATA)>

<!ELEMENT cdr EMPTY>

<!ATTLIST request method CDATA #REQUIRED>

<!ATTLIST request type CDATA #IMPLIED>

<!ATTLIST response method CDATA #REQUIRED>

<!ATTLIST response type CDATA #IMPLIED>

<!ATTLIST response status CDATA #REQUIRED>

=== aloka-ts/CASGitRepo/src/com/baypackets/ase/testapps/b2b/b2b-config.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
 * Copyright Notice ============================================*
 * This file contains proprietary information of BayPackets, Inc.
 * Copying or reproduction without prior written approval is prohibited.
 * Copyright (c) 2004-2006 =====================================
 *
-->


<!DOCTYPE b2b-config 
   PUBLIC "-//Baypackets SIP Application Server//DTD B2B Test Servlet Config//EN"
   "http://www.baypackets.com/dtd/b2b-config.dtd">

<b2b-config>

	<sleep-intervals>
		<request method="INVITE" type="initial">5000</request>
	</sleep-intervals>
	
	<request-forwardings>
		<request-forwarding>
			<incoming-ip>*</incoming-ip>
			<outbound-ip>192.168.3.251</outbound-ip>
			<outbound-port>5060</outbound-port>
		</request-forwarding>
	</request-forwardings>
	
	<cdr/>

</b2b-config>
